export const shopActionTypes = Object.freeze({
  SET_COLLECTIONS: 'SET_COLLECTIONS',
  FETCH_COLLECTIONS: 'FETCH_COLLECTIONS',
  FETCH_COLLECTIONS_SUCCESS: 'FETCH_COLLECTIONS_SUCCESS',
  FETCH_COLLECTIONS_ERROR: 'FETCH_COLLECTIONS_ERROR'
});
