export const userActionTypes = Object.freeze({
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_IN_WITH_GOOGLE_START: 'SIGN_IN_WITH_GOOGLE_START',
  SIGN_IN_WITH_GOOGLE_SUCCESS: 'SIGN_IN_WITH_GOOGLE_SUCCESS',
  SIGN_IN_WITH_GOOGLE_ERROR: 'SIGN_IN_WITH_GOOGLE_ERROR',
  SIGN_IN_WITH_EMAIL_START: 'SIGN_IN_WITH_EMAIL_START',
  SIGN_IN_WITH_EMAIL_SUCCESS: 'SIGN_IN_WITH_EMAIL_SUCCESS',
  SIGN_IN_WITH_EMAIL_ERROR: 'SIGN_IN_WITH_EMAIL_ERROR'
});
