export const userActionTypes = Object.freeze({
  SET_CURRENT_USER: 'SET_CURRENT_USER',
  SIGN_IN_WITH_GOOGLE_START: 'SIGN_IN_WITH_GOOGLE_START',
  SIGN_IN_WITH_GOOGLE_SUCCESS: 'SIGN_IN_WITH_GOOGLE_SUCCESS',
  SIGN_IN_WITH_GOOGLE_ERROR: 'SIGN_IN_WITH_GOOGLE_ERROR',
  SIGN_IN_WITH_EMAIL_START: 'SIGN_IN_WITH_EMAIL_START',
  SIGN_IN_WITH_EMAIL_SUCCESS: 'SIGN_IN_WITH_EMAIL_SUCCESS',
  SIGN_IN_WITH_EMAIL_ERROR: 'SIGN_IN_WITH_EMAIL_ERROR',
  CHECK_USER_SESSION: 'CHECK_USER_SESSION',
  CHECK_USER_SESSION_SUCCESS: 'CHECK_USER_SESSION_SUCCESS',
  CHECK_USER_SESSION_ERROR: 'CHECK_USER_SESSION_ERROR',
  LOGOUT_USER: 'LOGOUT_USER',
  LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
  REGISTER_USER: 'REGISTER_USER',
  REGISTER_USER_SUCCESS: 'REGISTER_USER_SUCCESS',
  REGISTER_USER_ERROR: 'REGISTER_USER_ERROR'
});
